Data no longer in the scripts

diff --git a/lexer/test/scanner b/lexer/test/scanner
--- a/lexer/test/scanner
+++ b/lexer/test/scanner
@@ -1,71 +1,86 @@
 #!/bin/bash
 
 program="$( basename "$0" )"
-shift
-exec=
-bold=`tput bold`
-normal=`tput sgr0`
+exe=
+old=
+save=
+verbose=
+current=
+results=
+tmpfile="test/check"
 
 function errWith {
   echo "$1" >& 2
   exit 1
 }
 
+bold=`tput bold`
+normal=`tput sgr0`
+uline=`tput smul`
+green=`tput setaf 2`
+red=`tput setaf 1`
+
+function execerror {
+  echo "${bold}${uline}${red}ERROR${normal} $1"
+}
+
 function testit {
-  echo "${bold}Testing:${normal} $1"
-  echo -n "${bold}Output:${normal} "
-  echo "$1" | "$exec"
+  current="$( basename "$1" )"
+  results="test/$old/$current"
+  echo "${bold}Testing:${normal} ${uline}${current}${normal}"
+  test -n "$verbose" && cat "$1"
+  cat "$1" | "$exe" &> "$tmpfile"
+  if [ $? -ne 0 ] ; then
+    execerror "Error testing $program with $current"
+  elif [ -n "$save" ] ; then
+    mv "$tmpfile" "$results"
+  elif [ ! -e "$results" ] ; then
+    execerror "Cannot check results -- standard does not exist"
+  else
+    if [ -n "$verbose" ] ; then
+      echo -n "${bold}Output:${normal} "
+      cat "$tmpfile"
+    fi
+    echo -n "${bold}Results:${normal} "
+    diff -q "$tmpfile" "$results" &> /dev/null
+    if [ $? -eq 0 ] ; then
+      echo "${bold}${green}PASS${normal}"
+    else
+      echo "${bold}${red}FAIL${normal}"
+    fi
+    rm "$tmpfile"
+  fi
   echo ""
 }
 
 case "$program" in
   scanner)
-        exec="./streams"
+        exe="./streams"
+        old="expect-scanner"
         ;;
   parser)
-        exec="./inspect"
+        exe="./inspect"
+        old="expect-parser"
         ;;
   *)
         errWith "Unknown test program $program"
         ;;
 esac
 
-test -e "$exec" || errWith "Testing $program but $exec unavailable"
-test -f "$exec" || errWith "Testing $program but $exec is not a file"
-test -x "$exec" || errWith "Testing $program but $exec unexecutable"
+while getopts "sv" OPTION ; do
+  case "$OPTION" in
+    s) save=1 ;;
+    v) verbose=1 ;;
+    ?) errWith "Unknown option; aborting" ;;
+  esac
+done
+shift $(($OPTIND - 1))
 
+test -e "$exe" || errWith "Testing $program but $exe unavailable"
+test -f "$exe" || errWith "Testing $program but $exe is not a file"
+test -x "$exe" || errWith "Testing $program but $exe unexecutable"
 
-testit 'class List {
-}'
-
-testit 'class List {
-  public {
-    init(Int a) {
-    }
-  }
-}'
-
-testit 'class List {
-  public {
-    String stringId(String in) {
-    }
-  }
-}'
-
-testit 'class List {
-  public {
-    init(Int a) {
-    }
-    String stringId(String in) {
-    }
-  }
-}'
-
-testit 'class List {
-  public {
-    init(Int a) {
-      5+4;
-    }
-  }
-}'
+for atest in test/tests/* ; do
+  testit "$atest"
+done
 
